[supervisord]
nodaemon=true
user=root
logfile=/app/data/logs/supervisord.log
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/nginx-access.log
stdout_logfile_maxbytes=0
stderr_logfile=/app/data/logs/nginx-error.log
stderr_logfile_maxbytes=0

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 10
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/data/logs/uvicorn-access.log
stdout_logfile_maxbytes=0
stderr_logfile=/app/data/logs/uvicorn-error.log
stderr_logfile_maxbytes=0
environment=SERVE_STATIC=true
